require "protobuf"

# Hand-written Crystal proto bindings for temporal.api.enums.v1.*
# Covers: workflow.proto, common.proto, failed_cause.proto

module Temporal
  module Api
    module Enums
      module V1
        enum WorkflowIdReusePolicy
          WORKFLOWIDREUSEPOLICYUNSPECIFIED          = 0
          WORKFLOWIDREUSEPOLICYALLOWDUPLICATE       = 1
          WORKFLOWIDREUSEPOLICYALLOWDUPLICATEFAILEDONLY = 2
          WORKFLOWIDREUSEPOLICYREJECTDUPLICATE      = 3
          WORKFLOWIDREUSEPOLICYTERMINATEIFRUNNING   = 4
        end

        enum WorkflowIdConflictPolicy
          WORKFLOWIDCONFLICTPOLICYUNSPECIFIED       = 0
          WORKFLOWIDCONFLICTPOLICYFAIL              = 1
          WORKFLOWIDCONFLICTPOLICYUSEEXISTING       = 2
          WORKFLOWIDCONFLICTPOLICYTERMINATEEXISTING = 3
        end

        enum ParentClosePolicy
          PARENTCLOSEPOLICYUNSPECIFIED  = 0
          PARENTCLOSEPOLICYTERMINATE    = 1
          PARENTCLOSEPOLICYABANDON      = 2
          PARENTCLOSEPOLICYREQUESTCANCEL = 3
        end

        enum ContinueAsNewInitiator
          CONTINUEASNEWINITIATORUNSPECIFIED  = 0
          CONTINUEASNEWINITIATORWORKFLOW     = 1
          CONTINUEASNEWINITIATORRETRY        = 2
          CONTINUEASNEWINITIATORCRONSCHEDULE = 3
        end

        enum WorkflowExecutionStatus
          WORKFLOWEXECUTIONSTATUSUNSPECIFIED   = 0
          WORKFLOWEXECUTIONSTATUSRUNNING       = 1
          WORKFLOWEXECUTIONSTATUSCOMPLETED     = 2
          WORKFLOWEXECUTIONSTATUSFAILED        = 3
          WORKFLOWEXECUTIONSTATUSCANCELED      = 4
          WORKFLOWEXECUTIONSTATUSTERMINATED    = 5
          WORKFLOWEXECUTIONSTATUSCONTINUEDASNEW = 6
          WORKFLOWEXECUTIONSTATUSTIMEDOUT      = 7
        end

        enum RetryState
          RETRYSTATEUNSPECIFIED           = 0
          RETRYSTATEINPROGRESS            = 1
          RETRYSTATENONRETRYABLEFAILURE   = 2
          RETRYSTATETIMEOUT               = 3
          RETRYSTATEMAXIMUMATTEMPTSREACHED = 4
          RETRYSTATERETRYPOLICYNOTSET     = 5
          RETRYSTATEINTERNALSERVERERROR   = 6
          RETRYSTATECANCELREQUESTED       = 7
        end

        enum TimeoutType
          TIMEOUTTYPEUNSPECIFIED    = 0
          TIMEOUTTYPESTARTTOCLOSE   = 1
          TIMEOUTTYPESCHEDULETOSTART = 2
          TIMEOUTTYPESCHEDULETOCLOSE = 3
          TIMEOUTTYPEHEARTBEAT      = 4
        end

        enum HistoryEventFilterType
          HISTORYEVENTFILTERTYPEUNSPECIFIED = 0
          HISTORYEVENTFILTERTYPEALLEVENT    = 1
          HISTORYEVENTFILTERTYPECLOSEEVENT  = 2
        end

        enum QueryRejectCondition
          QUERYREJECTCONDITIONUNSPECIFIED   = 0
          QUERYREJECTCONDITIONNOTOPEN       = 1
          QUERYREJECTCONDITIONNOREALLYOPEN  = 2
        end

        enum EventType
          EVENTTYPEUNSPECIFIED                                    = 0
          EVENTTYPEWORKFLOWEXECUTIONSTARTED                       = 1
          EVENTTYPEWORKFLOWEXECUTIONCOMPLETED                     = 2
          EVENTTYPEWORKFLOWEXECUTIONFAILED                        = 3
          EVENTTYPEWORKFLOWEXECUTIONTIMEDOUT                      = 4
          EVENTTYPEWORKFLOWTASKSCHEDULED                          = 5
          EVENTTYPEWORKFLOWTASKSTARTED                            = 6
          EVENTTYPEWORKFLOWTASKCOMPLETED                          = 7
          EVENTTYPEWORKFLOWTASKTIMEDOUT                           = 8
          EVENTTYPEWORKFLOWTASKFAILED                             = 9
          EVENTTYPEACTIVITYTASKSCHEDULED                          = 10
          EVENTTYPEACTIVITYTASKSTARTED                            = 11
          EVENTTYPEACTIVITYTASKCOMPLETED                          = 12
          EVENTTYPEACTIVITYTASKFAILED                             = 13
          EVENTTYPEACTIVITYTASKTIMEDOUT                           = 14
          EVENTTYPEACTIVITYTASKCANCELREQUESTED                    = 15
          EVENTTYPEACTIVITYTASKCANCELED                           = 16
          EVENTTYPETIMERFIRED                                     = 17
          EVENTTYPETIMERCANCELREQUESTED                           = 18
          EVENTTYPETIMERCANCELED                                  = 19
          EVENTTYPEWORKFLOWEXECUTIONCANCELREQUESTED               = 20
          EVENTTYPEWORKFLOWEXECUTIONCANCELED                      = 21
          EVENTTYPEREQUESTEDCANCELEXTERNALWORKFLOWEXECUTIONINITIALIZED = 22
          EVENTTYPEREQUESTEDCANCELEXTERNALWORKFLOWEXECUTIONRECORDED    = 23
          EVENTTYPEREQUESTEDCANCELEXTERNALWORKFLOWEXECUTIONFAILED      = 24
          EVENTTYPEEXTERNALWORKFLOWEXECUTIONCANCELREQUESTED             = 25
          EVENTTYPEMARKERRECORDED                                 = 25
          EVENTTYPEWORKFLOWEXECUTIONSIGNALED                      = 26
          EVENTTYPEWORKFLOWEXECUTIONTERMINATED                    = 27
          EVENTTYPEWORKFLOWEXECUTIONCONTINUEDASNEW                = 28
          EVENTTYPESTARTCHILDWORKFLOWEXECUTIONINITIALIZED         = 29
          EVENTTYPESTARTCHILDWORKFLOWEXECUTIONFAILED              = 30
          EVENTTYPECHILDWORKFLOWEXECUTIONSTARTED                  = 31
          EVENTTYPECHILDWORKFLOWEXECUTIONCOMPLETED                = 32
          EVENTTYPECHILDWORKFLOWEXECUTIONFAILED                   = 33
          EVENTTYPECHILDWORKFLOWEXECUTIONCANCELED                 = 34
          EVENTTYPECHILDWORKFLOWEXECUTIONTIMEDOUT                 = 35
          EVENTTYPECHILDWORKFLOWEXECUTIONTERMINATED               = 36
          EVENTTYPESIGNALEXTERNALWORKFLOWEXECUTIONINITIALIZED     = 37
          EVENTTYPESIGNALEXTERNALWORKFLOWEXECUTIONFAILED          = 38
          EVENTTYPEEXTERNALWORKFLOWEXECUTIONSIGNALED              = 39
          EVENTTYPEUPSERTWORKFLOWSEARCHATTRIBUTES                 = 41
          EVENTTYPEWORKFLOWEXECUTIONUPDATEADMITTED               = 42
          EVENTTYPEWORKFLOWEXECUTIONUPDATEACCEPTED               = 43
          EVENTTYPEWORKFLOWEXECUTIONUPDATECOMPLETED              = 44
          EVENTTYPEWORKFLOWPROPERTIESMODIFIED                    = 45
          EVENTTYPEWORKFLOWEXECUTIONUPDATEREQUESTED              = 46
        end

        enum TaskQueueKind
          TASKQUEUEKINDUNSPECIFIED = 0
          TASKQUEUEKINDNORMAL      = 1
          TASKQUEUEKINDSTICKY      = 2
        end

        enum ApplicationErrorCategory
          APPLICATIONERRORCATEGORYUNSPECIFIED = 0
          APPLICATIONERRORCATEGORYBENIGN      = 1
        end

        enum ResetReapplyType
          RESETREAPPLYTYPEUNSPECIFIED = 0
          RESETREAPPLYTYPESIGNAL      = 1
          RESETREAPPLYTYPEALLCOMMANDS = 2
          RESETREAPPLYTYPENONE        = 3
        end

        enum ResetReapplyExcludeType
          RESETREAPPLYEXCLUDETYPEUNSPECIFIED = 0
          RESETREAPPLYEXCLUDETYPESIGNAL      = 1
        end

        enum VersioningBehavior
          VERSIONINGBEHAVIORUNSPECIFIED = 0
          VERSIONINGBEHAVIORPINNED      = 1
          VERSIONINGBEHAVIORAUTOUPGRADE = 2
        end

        enum WorkflowTaskFailedCause
          WORKFLOWTASKFAILEDCAUSEUNSPECIFIED                              = 0
          WORKFLOWTASKFAILEDCAUSEUNHANDLEDCOMMAND                         = 1
          WORKFLOWTASKFAILEDCAUSEBADSCHEDULEACTIVITYATTRIBUTES            = 2
          WORKFLOWTASKFAILEDCAUSEBADREQUESTCANCELACTIVITYATTRIBUTES       = 3
          WORKFLOWTASKFAILEDCAUSEBADSTARTTIMERATTRIBUTES                  = 4
          WORKFLOWTASKFAILEDCAUSEBADCANCELTIMERATTRIBUTES                 = 5
          WORKFLOWTASKFAILEDCAUSEBADRECORDMARKERATTRIBUTES                = 6
          WORKFLOWTASKFAILEDCAUSEBADCOMPLETEWORKFLOWEXECUTIONATTRIBUTES   = 7
          WORKFLOWTASKFAILEDCAUSEBADFAILWORKFLOWEXECUTIONATTRIBUTES       = 8
          WORKFLOWTASKFAILEDCAUSEBADCANCELWORKFLOWEXECUTIONATTRIBUTES     = 9
          WORKFLOWTASKFAILEDCAUSEBADCANCELEXTERNALWORKFLOWEXECUTIONATTRIBUTES = 10
          WORKFLOWTASKFAILEDCAUSEBADCONTINUEASNEWATTRIBUTES               = 11
          WORKFLOWTASKFAILEDCAUSESTARTTIMERDUPLICATE                      = 12
          WORKFLOWTASKFAILEDCAUSERESETSTICKYTASKQUEUE                     = 13
          WORKFLOWTASKFAILEDCAUSEWORKFLOWWORKERUNHANDLEDFAILURE           = 14
          WORKFLOWTASKFAILEDCAUSEBADSIGNALWORKFLOWEXECUTIONATTRIBUTES     = 15
          WORKFLOWTASKFAILEDCAUSEBADSTARTCHILDEXECUTIONATTRIBUTES         = 16
          WORKFLOWTASKFAILEDCAUSENONDETERMINISTICERROR                    = 24
        end

        enum NexusHandlerErrorRetryBehavior
          NEXUSHANDLERERRORRETRYUNSPECIFIED = 0
          NEXUSHANDLERERRORRETRYRETRYABLE   = 1
          NEXUSHANDLERERRORRETRYNONRETRYABLE = 2
        end
      end
    end
  end
end
